export type TikTokEmbedRef = {
    play: () => void;
    pause: () => void;
    seekTo: (seconds: number) => void;
    mute: () => void;
    unMute: () => void;
    navigateTo: (index: number) => void;
    onPlayerReady?: () => void;
    onStateChange?: (state: number) => void;
    onCurrentTime?: (currentTime: number, duration: number) => void;
    onMute?: (muted: boolean) => void;
    onVolumeChange?: (volume: number) => void;
    onError?: (code: number) => void;
    onImageChange?: (index: number) => void;
};
type Props = {
    postId: string;
    height?: number;
    width?: number;
    autoplay?: boolean;
    loop?: boolean;
    showMusicInfo?: boolean;
    showDescription?: boolean;
    controls?: boolean;
    progressBar?: boolean;
    playButton?: boolean;
    volumeControl?: boolean;
    fullscreenButton?: boolean;
    timestamp?: boolean;
    rel?: boolean;
    nativeContextMenu?: boolean;
    closedCaption?: boolean;
    onPlayerReady?: () => void;
    onStateChange?: (state: number) => void;
    onCurrentTime?: (currentTime: number, duration: number) => void;
    onMute?: (muted: boolean) => void;
    onVolumeChange?: (volume: number) => void;
    onError?: (code: number) => void;
    onImageChange?: (index: number) => void;
};
declare const TikTokEmbedPlayer: import("react").ForwardRefExoticComponent<Props & import("react").RefAttributes<TikTokEmbedRef>>;
export default TikTokEmbedPlayer;
